# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8479c9857bb1f66b689a9b3cd3e96a3d"
name = "popup-banner"
application_url = "https://popup-cro-sidebar--development.gadget.app/api/shopify/install-or-render"
embedded = true

[build]
dev_store_url = "variant-reorder-apptest.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://popup-cro-sidebar--development.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
